---
target_config:
  fabric_modules: '{{ target_fabric_modules }}'
  storage_objects: '{{ target_storage_objects }}'
  targets: '{{ target_targets }}'

target_fabric_modules: []
target_storage_objects: []
target_targets: []

target_default_fabric_module:
  name: iscsi
  discovery_enable_auth: true
  discovery_userid: ''
  discovery_password: ''
  discovery_mutual_userid: ''
  discovery_mutual_password: ''

target_default_storage_object:
  alua_tpgs: ['{{ target_default_alua_tpg }}']
  attributes:
    alua_support: 1
    block_size: 512
    emulate_3pc: 1
    emulate_caw: 1
    emulate_dpo: 1
    emulate_fua_read: 1
    emulate_fua_write: 1
    emulate_model_alias: 1
    emulate_pr: 1
    emulate_rest_reord: 0
    emulate_rsoc: 1
    emulate_tas: 1
    emulate_tpu: 0
    emulate_tpws: 0
    emulate_ua_intlck_ctrl: 0
    emulate_write_cache: 0
    enforce_pr_isids: 1
    force_pr_aptpl: 0
    is_nonrot: 0
    max_unmap_block_desc_count: 0
    max_unmap_lba_count: 0
    max_write_same_len: 65535
    optimal_sectors: 65528
    pgr_support: 1
    pi_prot_format: 0
    pi_prot_type: 0
    pi_prot_verify: 0
    queue_depth: 64
    submit_type: 0
    unmap_granularity: 0
    unmap_granularity_alignment: 0
    unmap_zeroes_data: 0
  plugin: block
  readonly: false
  write_back: false

target_default_alua_tpg:
  alua_access_state: 0
  alua_access_status: 0
  alua_access_type: 3
  alua_support_active_nonoptimized: 1
  alua_support_active_optimized: 1
  alua_support_offline: 1
  alua_support_standby: 1
  alua_support_transitioning: 1
  alua_support_unavailable: 1
  alua_write_metadata: 0
  implicit_trans_secs: 0
  name: default_tg_pt_gp
  nonop_delay_msecs: 100
  preferred: 0
  tg_pt_gp_id: 0
  trans_delay_msecs: 0

target_default_target:
  fabric: iscsi
  parameters:
    cmd_completion_affinity: '-1'
  tpgs: []

target_default_tpg:
  attributes:
    authentication: 1
    cache_dynamic_acls: 1
    default_cmdsn_depth: 64
    default_erl: 0
    demo_mode_discovery: 1
    demo_mode_write_protect: 1
    fabric_prot_type: 0
    generate_node_acls: 0
    login_keys_workaround: 1
    login_timeout: 15
    prod_mode_write_protect: 0
    t10_pi: 0
    tpg_enabled_sendtargets: 1
  enable: true
  luns: []
  node_acls: []
  parameters:
    AuthMethod: CHAP
    DataDigest: CRC32C,None
    DataPDUInOrder: 'Yes'
    DataSequenceInOrder: 'Yes'
    DefaultTime2Retain: '20'
    DefaultTime2Wait: '2'
    ErrorRecoveryLevel: '0'
    FirstBurstLength: '65536'
    HeaderDigest: CRC32C,None
    IFMarkInt: Reject
    IFMarker: 'No'
    ImmediateData: 'Yes'
    InitialR2T: 'Yes'
    MaxBurstLength: '262144'
    MaxConnections: '1'
    MaxOutstandingR2T: '1'
    MaxRecvDataSegmentLength: '8192'
    MaxXmitDataSegmentLength: '262144'
    OFMarkInt: Reject
    OFMarker: 'No'
    TargetAlias: LIO Target
  portals: ['{{ target_default_portal }}']
  tag: 1

target_default_lun:
  alua_tg_pt_gp_name: default_tg_pt_gp
  index: 1

target_default_node_acl:
  attributes:
    authentication: -1
    dataout_timeout: 3
    dataout_timeout_retries: 5
    default_erl: 0
    nopin_response_timeout: 30
    nopin_timeout: 15
    random_datain_pdu_offsets: 0
    random_datain_seq_offsets: 0
    random_r2t_offsets: 0
  chap_userid: ''
  chap_password: ''
  chap_mutual_userid: ''
  chap_mutual_password: ''
  mapped_luns: []

target_default_portal:
  ip_address: 0.0.0.0
  iser: false
  offload: false
  port: 3260

target_default_mapped_lun:
  - index: 1
    tpg_lun: 1
    write_protect: false
...
