---
iscsi_node_acl:
  chap_userid: initiator
  chap_password: '{{ lookup("ansible.builtin.password",
    "secrets/iscsi_{{ inventory_hostname }}_password.txt", length=26) }}'
  chap_mutual_userid: initiator_mutual
  chap_mutual_password: '{{ lookup("ansible.builtin.password",
    "secrets/iscsi_{{ inventory_hostname }}_mutual_password.txt",
    length=26) }}'
  mapped_luns:
    - alias: '{{ lookup("ansible.builtin.password",
        "secrets/iscsi_{{ inventory_hostname }}_tpg1_lun1.txt",
        chars="01234567890abcdef", length=10) }}'
  node_wwn: iqn.2025-03.ru.abegorov:gfs2:{{ inventory_hostname }}
...
